### ISSUE TITLE
[Bug][IN-18281] Not work with iOS16

### ISSUE THREAD

**Issue by Phantomxm2021** [Unity-Technologies/uaal-example#73]
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/82647748/190960644-17771cb3-b4e7-4ca2-b046-d870d60d36a4.png">

**Comment by hervenivon** [comment]
We are facing the same issue.

It only happens when the device is connected to Xcode 14, and the device is iOS16. The app runs smoothly when not connected to Xcode or when the iOS version is iOS15.

In addition, we also have the following message in the logs: `warning: UnityFramework was compiled with optimization - stepping may behave oddly; variables may not be available.`

**Comment by ROBYER1** [comment]
Is it just the debugging/console in Xcode that doesn't work?

**Comment by hervenivon** [comment]
With this example, it is impossible to launch the app on iOS 16 if it is connected to Xcode. If not connected to Xcode, it works.

1. Connect your device to the mac with a cable
2. Build in Xcode and deploy to your iOS 16 device
3. **You can't continue** and see the above error
4. Unplug the cable
5. Relaunch the app just deployed from Xcode
6. The app works

The issue is you can't debug you app if the device is on iOS 16.

**Comment by Phantomxm2021** [comment]
> Is it just the debugging/console in Xcode that doesn't work?

NO, some unity features can not working~ e.g. ARFoundation will be black screen (Work in iOS15)

**Comment by Phantomxm2021** [comment]
> 

Yes, I do it. But some unity features can not working.  e.g. ARFoundation will be black screen (Work in iOS15)

**Comment by Phantomxm2021** [comment]
> With this example, it is impossible to launch the app on iOS 16 if it is connected to Xcode. If not connected to Xcode, it works.
> 
> 1. Connect your device to the mac with a cable
> 2. Build in Xcode and deploy to your iOS 16 device
> 3. **You can't continue** and see the above error
> 4. Unplug the cable
> 5. Relaunch the app just deployed from Xcode
> 6. The app works
> 
> The issue is you can't debug you app if the device is on iOS 16.

Yes, I do it. But some unity features can not working. e.g. ARFoundation will be black screen (Work in iOS15)

**Comment by hervenivon** [comment]
IN-18281 reference on Unity forum: https://forum.unity.com/threads/in-18281-uaal-not-work-on-ios16.1343546/

The issue is closed. What do we need to do to make it work?

**Comment by adam-cove** [comment]
For anyone still struggling, the workaround is disabling the Thread Performance Checker in your scheme > run > diagnostics (screenshot below)

![image](https://user-images.githubusercontent.com/36454559/214027748-73c3e6cb-14ac-4a42-8da4-3b99b7e0d911.png)
